### PR TITLE
Fixed nasty quest planner bugs

### PR DESCRIPTION
**Pull request by Drakons**
ATTENTION!
ONLY APPLY THIS BUGFIXES AFTER ALL QUESTS CONTAINING NONASCII CHARS ARE REMOVED FROM THE WEBSITE OTHERWISE IT WILL CRASH THE SITES WITH A ENCODING ERROR!

Fixed those two bugs below:

http://illarion.org/mantis/view.php?id=10857
http://illarion.org/mantis/view.php?id=10238

Bugs were e.g.:
Reset of quest-texts on editing which contain non-ascii chars as ö,ä,ü etc.
Reset of dates like 29. March 2016 to 01. March 2016.

Also done some forgotten translations in the us_questplanner.
edit: sry for the merge - i recommend to flatten the history of this pull

### CODE REVIEW

**Comment by mkaring** [comment]
I am not sure if the UTF-8 stuff is really needed. The decoding and encoding shouldn't be required, because everything should handle UTF-8 properly. The database is set to UTF-8 and the webpage should send UTF-8 strings to php. I am not absolutely sure why this is required.

**Comment by Drakons** [comment]
A I thought the database does not use UTF-8 as the webpage already has used encode_utf8(). When I'm back from work I'll check if removing both decode and encode will work too - if yes I'll commit this to this request as it is indeed a cleaner (and more stable) solution.

**Comment by mkaring** [comment]
The database should handle utf8 fine. The main issue with the UTF 8 was that the homepage did fallback to the default system encoding in case the page was not fully encoded as UTF-8. This happened at time because the original homepage was encoded in ISO-8859-1. And we never managed to fix that for all pages. But for most newer parts of the homepage, such as the quest planner, this should be fixed and everything should work with UTF-8.

**Comment by Drakons** [comment]
Tested without utf8_decode and removed utf8_encode function in act_quest_save.php. Works as intended, commited and pull request refreshed.

**Pull request merged**
